### ISSUE TITLE
Missing modules?

### ISSUE THREAD

**Issue by hyperlink** [auramagi/swiftui-first-sample#1]
<img width="866" alt="image" src="https://github.com/auramagi/swiftui-first-sample/assets/133309/d83a7e5c-6889-414e-b83c-569f0287e105">

Looks like some modules are not included?

**Comment by auramagi** [comment]
Please open `Dogs.xcworkspace` instead of `Dogs.xcodeproj`.

`Core` is a transitive dependency that will get included through `LiveApp`.
